name: Sync Vencord Dev
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

env:
    WORKFLOW_TOKEN: ${{ secrets.ETOKEN }}
    UPSTREAM_URL: "https://github.com/Vendicated/Vencord.git"
    UPSTREAM_BRANCH: "dev"
    DOWNSTREAM_BRANCH: "dev"

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Sync Vencord Dev
              id: sync
              uses: verticalsync/sync-upstream-repo@master
              with:
                  upstream_repo: ${{ env.UPSTREAM_URL }}
                  upstream_branch: ${{ env.UPSTREAM_BRANCH }}
                  downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
                  token: ${{ env.WORKFLOW_TOKEN }}
